FoodOrder/FoodOrder/Models/CategoryViewModel.cs
using FoodOrder.Shared.Models;

namespace FoodOrder.Models
{
    public class CategoryViewModel
    {
        public List<Category> Categories { get; set; }
        public List<Tuple<string,int,int>> MostPopular { get; set; }

        public CategoryViewModel()
        {
            Categories = new List<Category>();
            MostPopular = new List<Tuple<string,int,int>>();
        }
    }
}

FoodOrder/FoodOrder/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FoodOrder.Models;
using FoodOrder.Shared.Services;
using FoodOrder.Shared.Models;

namespace FoodOrder.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly IFoodOrderService service;

        public CategoriesController(IFoodOrderService service)
        {
            this.service = service;
        }

        // GET: Categories
        public IActionResult Index()
        {
            try
            {
                var list = service.GetCategories();
                TempData["filterString"] = null;
                List<Tuple<string, int, int>> MostPopular = new List<Tuple<string, int, int>>();
                foreach (Category cat in list)
                {
                    foreach (Item item in cat.Items)
                    {
                        MostPopular.Add(new Tuple<string, int, int>(item.Name, item.Id, item.Orders.Count));
                    }
                }
                MostPopular = MostPopular.OrderByDescending(x => x.Item3).Take(10).ToList();
                return View(new CategoryViewModel()
                {
                    Categories = list,
                    MostPopular = MostPopular
                });
            }
            catch (Exception)
            {
                return NotFound();
            }
        }
        public IActionResult Details(int id)
        {
            try
            {
                Category list = service.GetCategoryDetails(id);
                if (TempData.Peek("filterString") != null)
                {
                    string filterString = (string)TempData.Peek("filterString")!;
                    list.Items = list.Items.Where(x => x.Name.ToLower().Contains(filterString.Trim().ToLower())).ToList();
                }
                return View(list);
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(int id, string filterString="")
        {
            try
            {
                Category category = service.GetCategoryDetails(id);
                if (filterString != null && filterString!="")
                {
                    category.Items = category.Items.Where(x => x.Name.ToLower().Contains(filterString.Trim().ToLower())).ToList();
                    TempData["filterString"] = filterString;
                }
                return View(category);
            }
            catch
            {
                return NotFound();
            }
        }
    }
}

FoodOrder/FoodOrder/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FoodOrder.Models;
using FoodOrder.Shared.Services;
using FoodOrder.Shared.Models;
using Microsoft.AspNetCore.Server.IIS;

namespace FoodOrder.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IFoodOrderService service;

        public OrdersController(IFoodOrderService service)
        {
            this.service = service;
        }
        public IActionResult Index()
        {
            List<Item> items = new List<Item>();
            if (HttpContext.Session.GetString("Basket") != null)
            {
                items = HttpContext.Session.GetString("Basket")!.Split(',', StringSplitOptions.RemoveEmptyEntries).Select(x => service.GetItemById(int.Parse(x))).ToList();
            }
            int sum = 0;
            items.ForEach(x => sum += x.Price);
           return View(new ItemViewModel()
           {
               Items = items,
               Sum = sum
           });
        }
        public IActionResult AddToCart(int id,string returnUrl="")
        {
            Console.WriteLine(returnUrl);
            if (HttpContext.Session.GetString("Basket") == null)
            {
                HttpContext.Session.SetString("Basket","");
            }
            try
            {
                int sum = 0;
                List<string> items = HttpContext.Session.GetString("Basket")!.Split(',', StringSplitOptions.RemoveEmptyEntries).ToList();
                if (items.Contains(id.ToString())) throw new InvalidDataException("The item is already added, due to lack of stock, you can buy only one!");
                items.ForEach(x => sum += service.GetItemById(int.Parse(x)).Price);
                if (sum + service.GetItemById(id).Price > 20000) throw new InvalidDataException("The price is too high! Max is 20.000!");
                items.Add(id.ToString());
                HttpContext.Session.SetString("Basket", String.Join(',', items));
            }
            catch (InvalidDataException ex)
            {
                TempData["Success"] = false;
                TempData["Message"] = ex.Message;
                return RedirecToLocal(returnUrl);
            }
            catch
            {
                TempData["Success"] = false;
                TempData["Message"] = "Unable to retrieve Item info!";
                return RedirecToLocal(returnUrl);
            }
            TempData["Success"] = true;
            TempData["Message"] = "Item successfully added to Cart!";
            return RedirecToLocal(returnUrl);
        }
        public IActionResult DeleteFromCart(int id)
        {
            List<string> items = HttpContext.Session.GetString("Basket")!.Split(',', StringSplitOptions.RemoveEmptyEntries).ToList();
            items.Remove(id.ToString());
            HttpContext.Session.SetString("Basket", String.Join(',', items));
            return RedirectToAction(nameof(Index));
        }
        public IActionResult DeleteAll()
        {
            HttpContext.Session.SetString("Basket", "");
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Create()
        {
            if(HttpContext.Session.GetString("Basket")==null || HttpContext.Session.GetString("Basket") == "")
            {
                TempData["OrderError"] = true;
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(OrderViewModel vm)
        {
            if (ModelState.IsValid)
            {
                Order order = (Order)vm;
                order.Items = HttpContext.Session.GetString("Basket")!.Split(',', StringSplitOptions.RemoveEmptyEntries).Select(x => service.GetItemById(int.Parse(x))).ToList();
                if (service.AddOrder(order))
                {
                    TempData["Success"] = true;
                    TempData["Message"] = "Order successfully placed!";
                    HttpContext.Session.SetString("Basket", "");
                    return RedirectToAction(nameof(Index), "Categories");
                }
                else
                {
                    TempData["Success"] = false;
                    TempData["Message"] = "Unable to save to database!";
                    return RedirectToAction(nameof(Index), "Categories");
                }
            }
            return View(vm);
        }
        private IActionResult RedirecToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Index", "Categories");
            }
        }
    }
}

FoodOrder/FoodOrder/Views/Categories/Details.cshtml
@model FoodOrder.Shared.Models.Category

@using Microsoft.AspNetCore.Session;

@{
    ViewData["Title"] = "Foods and Beverages";
    object Message = TempData["Message"] ?? "";
}
@if (TempData["Success"] != null)
{
    @if ((bool)TempData["Success"]! == true)
    {
        <div class="bg-success rounded">@Message</div>
    }
    else
    {
        <div class="bg-danger rounded">@Message</div>
    }
}

<div>
    <h4>@Html.DisplayFor(model => model.Name)</h4>
    <hr />
    <form asp-action="Details" class="input-group mb-3">
        <input type="text" class="form-control" name="filterString" id="filterString" />
        <input type="number" class="visually-hidden" name="id" id="id" value="@Model.Id"/>
        <div class="input-group-append">
            <input type="submit" value="🔎" class="btn btn-primary"/>
        </div>
    </form>
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Price</th>
                <th>Description</th>
                <th>Spicy</th>
                <th>Vegetarian</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model.Items)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @if (item.Spicy)
                        {
                            <p>✔</p>
                        }
                        else
                        {
                            <p>❌</p>
                        }
                    </td>
                    <td>
                        @if (item.Vegetarian)
                        {
                            <p>✔</p>
                        }
                        else
                        {
                            <p>❌</p>
                        }
                    </td>
                    <td>
                        <a asp-area="" asp-action="AddToCart" asp-controller="Orders" asp-route-id="@item.Id" asp-route-returnUrl="@Context.Request.Path">🛒</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div>
    <a asp-action="Index" class="btn btn-primary">Back to Categories</a>
</div>

FoodOrder/FoodOrder/Views/Categories/Index.cshtml
@model CategoryViewModel

@{
    ViewData["Title"] = "Categories";
    object Message = TempData["Message"] ?? "";
}
@if (TempData["Success"] != null)
{
    @if ((bool)TempData["Success"]! == true)
    {
        <div class="bg-success rounded">@Message</div>
    }
    else
    {
        <div class="bg-danger rounded">@Message</div>
    }
}

<h1>Categories</h1>
<br />
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Categories) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Let's see!</a>
            </td>
        </tr>
}
    </tbody>
</table>
<br />
<h1>Top 10 Items</h1>
<br />
<ol class="list-group list-group-numbered">
@foreach(var item in Model.MostPopular)
{
    <li class="list-group-item d-flex justify-content-between align-items-start">
        <div class="ms-2 me-auto">
            <div class="fw-bold">
                @item.Item1
            </div>
        </div>
        <span class="btn btn-primary rounded-pill">
            <a asp-action="AddToCart" asp-route-id="@item.Item2" asp-route-returnUrl="@Context.Request.Path" asp-controller="Orders">🛒</a>
        </span>
    </li>
}
</ol>